### PR TITLE
Fix #378 (infra) - Support Sonar CSV and sysinfo data in infiltrate

### LINKED ISSUE #378: Add a sonar-raw channel to infiltrate?
If infiltrate could accept raw sonar csv data - probably with a "cluster" identifier added by sonar - on a dedicated channel then exfiltrate could probably be replaced by curl, simplifying the stack on the nodes quite a bit: curl has retry functionality with retry delay and number of retries, as well as retry conditions.

I'm noting this for future exploration.  There's a range of ways we could simplify the clients:

- removing exfiltrate and using curl (this bug + some simple tweaks to sonar)
- making sonar produce json and simplifying exfiltrate
- folding exfiltrate into sonar entirely

I'm not sure which is better, but having only sonar to worry about (I assume curl is everywhere, but I could be wrong) would be a win.

See also #336.

### PR DESCRIPTION
**Pull request by lars-t-hansen**
Infiltrate is rewritten using the better libraries, and has two new services: /sonar-freecsv and /sonar-sysinfo.  The old JSON services remain.

Exfiltrate has been rewritten and is now just a data forwarding agent, it does not inspect its data at all.

### CODE REVIEW

File: code/exfiltrate/exfiltrate.go [hunk 1]
```diff
@@ -1,62 +1,77 @@
-// `exfiltrate` - data forwarder for Sonar data, to run on HPC nodes.
+// `exfiltrate` - data forwarder for all sorts of data, to run on HPC nodes.
 //
-// Exfiltrate receives data on stdin, parses it, reformats it for transmission, and forwards it to a
-// network agent.  It attempts to do so reliably: if forwarding fails with some recoverable error it
-// will retry the sending later.  It will batch outputs when possible.  It will randomly pick a
-// sending time in a specified sending window, in order to offload the server without impacting the
-// quality or timing of measurement data.  Input formats, transmission formats, and agent addresses
-// are controlled by options.
+// Exfiltrate receives data on stdin and forwards it to a network agent, with some features:
```
Comment (lars-t-hansen) [inline code/exfiltrate/exfiltrate.go:3]: "network service" probably.

File: code/infiltrate/infiltrate.go [hunk 2]
```diff
@@ -48,43 +44,87 @@
...
+// /sonar-heartbeat
+//    Input is JSON-format Sonar heartbeat data: array of go-utils/sonarlog.SonarHeartbeat.  Input
+//    fields are checked against that record type: fields that are not known to the type are
+//    dropped.
+//
+// /sonar-freecsv?cluster=clusterName
+//    Input is "free CSV" format Sonar monitoring and heartbeat data, intermixed, one record per
+//    line.  If -match-user-and-cluster is used then the the user name provided by the HTTP
+//    connection must match the "cluster" parameter, which is always required.  Input fields are not
+//    checked - the records are always stored verbatim in the database, after checking the cluster.
```
Comment (lars-t-hansen) [inline code/infiltrate/infiltrate.go:64]: Records must have sensible `time` and `host` fields or they will be rejected.

File: code/infiltrate/infiltrate.go [hunk 3]
```diff
@@ -48,43 +44,87 @@
...
+//
+// /sysinfo?cluster=clusterName
+//    Input is JSON-format system information data: a single record of go-utils/config.SystemConfig.
+//    The cluster parameter is required; cluster name checking is as for /sonar-freecsv.
```
Comment (lars-t-hansen) [inline code/infiltrate/infiltrate.go:68]: The record must have sensible `timestamp` and `hostname` fields, or they will be rejected.

File: code/infiltrate/infiltrate.go [hunk 4]
```diff
@@ -48,43 +44,87 @@
...
+//
+// /sonar-heartbeat
+//    Input is JSON-format Sonar heartbeat data: array of go-utils/sonarlog.SonarHeartbeat.  Input
+//    fields are checked against that record type: fields that are not known to the type are
+//    dropped.
+//
+// /sonar-freecsv?cluster=clusterName
+//    Input is "free CSV" format Sonar monitoring and heartbeat data, intermixed, one record per
+//    line.  If -match-user-and-cluster is used then the the user name provided by the HTTP
+//    connection must match the "cluster" parameter, which is always required.  Input fields are not
```
Comment (lars-t-hansen) [inline code/infiltrate/infiltrate.go:63]: "Most" input fields ....

File: code/infiltrate/infiltrate.go [hunk 5]
```diff
@@ -276,163 +269,92 @@ func sonarHeartbeat(payload []byte, dataPath, clusterName string) (int, string,
...
+		return 400, "Bad parameters", "Bad parameters - missing or repeated 'cluster'"
 	}
+	cluster := vs[0]
+	var info config.SystemConfig
+	err := json.Unmarshal(payload, &info)
+	if err != nil {
+		return 400, "Bad content",
+			fmt.Sprintf("Bad content - can't unmarshal Sysinfo JSON: %v", err)
+	}
+	if info.Timestamp == "" {
```
Comment (lars-t-hansen) [inline code/infiltrate/infiltrate.go:317]: Hostname also.
